### ISSUE TITLE
cmake minimum version requirement

### ISSUE THREAD

**Issue by grayj2** [space-physics/wmm2020#5]
Installed via pip with `python -m pip install wmm2020`. Attempted to 'import wmm2020' in the python terminal and got the following error:

'''
>>> import wmm2020
* Extra verbosity turned on
Reading Script: /home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/setup.cmake
-- CMake 3.10.2
CMake Error at /home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/setup.cmake:11 (message):
  Please update CMake >= 3.12

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/__init__.py", line 1, in <module>
    from .base import wmm
  File "/home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/base.py", line 17, in <module>
    build()
  File "/home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/build.py", line 27, in build
    subprocess.check_call([exe, "-S", str(file), "-VV"])
  File "/home/<user>/miniconda3/envs/magnav/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/ctest', '-S', '/home/<user>/miniconda3/envs/magnav/lib/python3.7/site-packages/wmm2020/setup.cmake', '-VV']' returned non-zero exit status 255.
'''

Once i updated CMake >= 3.12, it fixed the issue.

Perhaps either add a note in your README to install an appropriate version of CMake or include the cmake version in your setup.cfg

**Comment by scivision** [comment]
fixed in v1.1.1
